spring.application.name=backend


# ==========================================
# LAB 01 - MySQL
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3307/security_lab
spring.datasource.username=labuser

# [LAB ONLY]
# 로컬 격리 실습을 단순하게 진행하기 위해
# 테스트 DB 비밀번호를 설정 파일에 직접 작성한다.
#
# [PRODUCTION]
# 실제 서비스에서는 DB 비밀번호를 Git에 포함하면 안 되며,
# 환경 변수 또는 AWS Secrets Manager 등의 비밀 관리 방식을 사용해야 한다.
spring.datasource.password=labpass

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver